#pragma once
void _charter6_chainNode_testCode();
void _charter6_chainList_testCode();
void _charter6_chainListWithIterator_testCode();
void _charter6_chainListWithIteratorExtend_testCode();
void _charter6_chainListCircular_testCode();
void _charter6_StudentRecord1_binSort_testCode();
void _charter6_StudentRecord2_binSort_testCode();
void _charter6_convex_hull();