#pragma once
void _charter7_array2D_pointer();
void _charter7_irregular_array2d();
void _charter7_matrixAdd();
void _charter7_matrixMultiply_sameSize();
void _charter7_matrixMultiply_differentSize();
void _charter7_matrixTranspose();
void _charter7_matrix_testCode();
void _charter7_diagonalMatrix();
void _charter7_tridiagonalMatrixRowMapping();
void _charter7_tridiagonalMatrixColMapping();
void _charter7_tridiagonalMatrixDiagMapping();
void _charter7_lowerTriangularMatrixRow();
void _charter7_lowerTriangularMatrixCol();
void _charter7_upperTriangularMatrixRow();
void _charter7_upperTriangularMatrixCol();
void _charter7_symmetric_matrix();
void _charter7_sparse_matrix();
