#pragma once
void _charter7_array2D_pointer();
void _charter7_irregular_array2d();
void _charter7_matrixAdd();
void _charter7_matrixMultiply_sameSize();
void _charter7_matrixMultiply_differentSize();
void _charter7_matrixTranspose();
void _charter7_matrix_testCode();
void _charter7_diagonalMatrix();
